[earth_engine]
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0b3y9tU4H2VJy\n3SrUNtyDt8I0BgYOBhY7CBIJAgMBAAECggEAD4vK1V1zgYFZy0oHhDmDw2pZ6QzI\n..."
client_email = "gee-service-account@ee-mawucano25.iam.gserviceaccount.com"
